In [1]:
from PortfolioOptimization import get_yearly_returns

In [2]:
max_risk = 0.15

In [3]:
from Portfolios.MeanAbsDev import MeanAbsDevPortfolio
weights, stats = get_yearly_returns(MeanAbsDevPortfolio, max_risk)

In [4]:
weights

    Year    XLY    XLP    XLE    XLF    XLV    XLI    XLB    XLK    XLU
0   2000  13.69   0.00  12.73   4.58  13.10  14.90  16.00  25.00   0.00
1   2001   0.00  22.12  22.14  23.82   0.00  11.70   0.00   0.00  20.21
2   2002  25.00   6.39   0.00   9.69  25.00   8.28  25.00   0.00   0.64
3   2003  10.31   6.40  14.92  15.54  25.00   2.84  25.00   0.00   0.00
4   2004  11.14  11.05  11.10  11.12  11.07  11.12  11.14  11.15  11.11
5   2005  11.11  11.09  11.18  11.10  11.06  11.12  11.11  11.08  11.14
6   2006   4.34   8.75  25.00  10.44  10.46   8.84   9.74   7.41  15.01
7   2007  11.12  11.10  11.13  11.12  11.08  11.10  11.12  11.10  11.13
8   2008   0.00  10.82  25.00   0.00   7.66  11.73  17.27  12.88  14.64
9   2009  15.03  25.00  14.85   0.00  23.42   3.60   0.00   0.00  18.10
10  2010  25.00   0.00   2.36  21.33   0.00   1.31  25.00  25.00   0.00
11  2011  11.15  11.10  11.13  11.10  11.06  11.15  11.13  11.10  11.07
12  2012  13.03  17.70  12.27   0.00  17.15   7.90   0.00  10.01  21.95
13  2013  11.14  11.10  11.08  11.16  11.12  11.11  11.11  11.11  11.06
14  2014  11.15  11.10  11.10  11.13  11.14  11.14  11.10  11.10  11.05
15  2015   9.37  12.17   0.00  12.05  16.73   9.85   8.29  13.34  18.21
16  2016  16.97  15.27   0.00  11.09  15.63   9.55   7.28  14.90   9.30
17  2017   2.26   0.85  25.00  18.78   0.00  15.88  13.47  11.34  12.43
18  2018  11.12  11.09  11.04  11.12  11.12  11.13  11.13  11.16  11.09
19  2019  22.85   7.28   0.00   0.48  25.00   0.02   0.00  19.37  25.00
20  2020  11.11  11.11  11.06  11.13  11.09  11.12  11.10  11.18  11.10
21  2021  25.00   6.59   0.00   1.58  10.26  11.37  19.27  25.00   0.92
22  2022  11.87   0.00  25.00  22.67   6.98   0.00  10.72  22.76   0.00
23  2023   0.00  14.38  25.00   9.75  13.84  12.27   8.85   0.00  15.91
24  2024  24.99   3.36   4.66  11.17   5.11  14.26  11.46  25.00   0.00

In [5]:
stats

    Year  Annual Return  Volatility  Sharpe Ratio  Max Drawdown
0   2000         -11.84       21.71       -0.5456        -18.44
1   2001         -11.15       15.84       -0.7037        -19.71
2   2002         -10.74       24.47       -0.4388        -26.35
3   2003          27.30       15.24        1.7917        -12.15
4   2004          14.24       10.67        1.3342         -6.00
5   2005           7.88       10.68        0.7375         -6.81
6   2006          17.06       11.40        1.4955         -8.39
7   2007           9.66       15.47        0.6243         -9.29
8   2008         -33.82       39.24       -0.8618        -45.29
9   2009          21.20       20.55        1.0319        -22.99
10  2010          18.48       20.96        0.8819        -18.10
11  2011           3.09       23.08        0.1341        -18.62
12  2012          11.58       10.35        1.1186         -7.05
13  2013          30.88       11.03        2.7989         -5.94
14  2014          13.33       10.98        1.2137         -7.05
15  2015           1.59       14.52        0.1098        -10.27
16  2016          10.86       12.09        0.8984         -7.70
17  2017          16.78        7.55        2.2223         -3.87
18  2018          -6.16       15.36       -0.4011        -18.47
19  2019          30.03       10.75        2.7935         -5.05
20  2020          10.41       35.61        0.2924        -36.90
21  2021          28.43       13.58        2.0935         -5.33
22  2022          -2.73       24.51       -0.1116        -18.31
23  2023           3.77       12.51        0.3014         -8.96
24  2024          19.35       13.53        1.4303         -9.30